/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "sli_bt_gattdb_def.h"

extern const sli_bt_gattdb_t gattdb;

#define gattdb_generic_attribute              1
#define gattdb_service_changed_char           3
#define gattdb_database_hash                  6
#define gattdb_client_support_features        8
#define gattdb_device_info                    9
#define gattdb_manufacturer_name_string       11
#define gattdb_model_number_string            14
#define gattdb_serial_number_string           17
#define gattdb_firmware_revision_string       20
#define gattdb_device_information             22
#define gattdb_device_name                    24
#define gattdb_appearance                     27
#define gattdb_light_state                    31
#define gattdb_trigger_source                 35
#define gattdb_source_address                 39


#endif // __GATT_DB_H
